AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS Patronus Micro Services
  InventoryNotification:
    Type: String
    Description: Inventory notification

Resources:

  InventoryCreateResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: inventory.loadSku
        Runtime: nodejs4.3
        Role:
          Fn::ImportValue:
            !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]

  InventoryPromiseResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: inventory.allocate
        Runtime: nodejs4.3
        Role:
          Fn::ImportValue:
            !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]



  InventoryResource:
         Type: AWS::Serverless::Function

         Properties:
           Handler: inventory.handler
           Runtime: nodejs4.3
           Role:
             Fn::ImportValue:
               !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
           Events:
             GetEvent:
               Type: Api
               Properties:
                 Path: /inventory/{CountryCode}/{SKU}
                 Method: get
                 RestApiId: atpCheck
